### ISSUE TITLE
如果远程服务器绑定域名，如何使用域名证书？

### ISSUE THREAD

**Issue by lukemin** [rchunping/https-proxy#1]
自签证书远端访问有点麻烦。

**Comment by rchunping** [comment]
签发一个域名证书，端口换成https标准端口443就行了

--proxy https://your-proxy-host

**Comment by rchunping** [comment]
如果 Let's Encrypt 签发的，
这样指定参数启动  -key domain.key -pem fullchain.cer

**Comment by lukemin** [comment]
./https-proxy --proxy https://mydomain -key path/domain.key -pem path/fullchain.cer "usr:pws"
这样对吗？

**Comment by rchunping** [comment]
假设你有一台机器 ip 1.2.3.4 和一个域名 mydomain.com
DNS设置 mydomain.com 指向 1.2.3.4
然后签发一个域名证书

```
./https-proxy --listen=":443" -proto=https -key path/mydomain.key -pem path/fullchain.cer -users "usr:pws"
```

然后其他地方用的时候可以直接用 https://mydomain.com 了
比如
```
curl --proxy https://usr:pws@mydomain.com  https://www.baidu.com
```

**Comment by lukemin** [comment]
但是我的vps上还有其他域名，如果监听443端口，其他域名就不能访问，如何解决？

**Comment by rchunping** [comment]
那试一下其他端口吧，看看这样行不行

```
./https-proxy --listen=":8080" -proto=https -key path/mydomain.key -pem path/fullchain.cer -users "usr:pws"
```

```
curl --proxy https://usr:pws@mydomain.com:8080  https://www.baidu.com
```

**Comment by lukemin** [comment]
好的，谢谢

**Comment by lukemin** [comment]
2019/08/13 15:16:56 http: TLS handshake error from 本地ip:14784: tls: first record does not look like a TLS handshake

**Comment by rchunping** [comment]
你指定了 -proto=https ，那么使用的时候必须作为https代理来用

```
curl --proxy https://mydomain
```

注意是 http**s**://mydomain  不是 http://mydomain

这样客户端和代理服务器连接的时候才会进行ssl加密
